SELECT B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(B.PRICE * BS.SALES) AS TOTAL_SALES FROM BOOK B
JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
JOIN BOOK_SALES BS ON B.BOOK_ID = BS.BOOK_ID
WHERE BS.SALES_DATE LIKE '2022-01%'
GROUP BY B.CATEGORY, A.AUTHOR_NAME
ORDER BY AUTHOR_ID, CATEGORY DESC

# SELECT A.AUTHOR_NAME, B.CATEGORY, B.PRICE, COUNT(B.BOOK_ID), SUM(BS.SALES) FROM BOOK B
# JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
# JOIN BOOK_SALES BS ON B.BOOK_ID = BS.BOOK_ID
# GROUP BY B.CATEGORY, A.AUTHOR_NAME