SELECT C.CAR_ID, C.CAR_TYPE, FLOOR((100-DP.DISCOUNT_RATE)/100 * C.DAILY_FEE*30) AS FEE FROM CAR_RENTAL_COMPANY_CAR C
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY RH ON C.CAR_ID = RH.CAR_ID
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN DP ON C.CAR_TYPE = DP.CAR_TYPE
WHERE DP.DURATION_TYPE='30일 이상'
      AND NOT EXISTS (
    SELECT 1
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY RH2
    WHERE RH2.CAR_ID = C.CAR_ID
      AND RH2.END_DATE > '2022-11-01'
      AND RH2.START_DATE < '2022-12-01'
)
GROUP BY C.CAR_ID
HAVING CAR_TYPE IN ('세단', 'SUV') AND (FEE >= 500000 AND FEE < 2000000)
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC