SELECT AI.ANIMAL_ID, AI.ANIMAL_TYPE, AI.NAME FROM ANIMAL_INS AI
WHERE SEX_UPON_INTAKE LIKE 'Intact%' 
AND AI.ANIMAL_ID IN (SELECT AO.ANIMAL_ID 
                    FROM ANIMAL_OUTS AO
                    WHERE AO.SEX_UPON_OUTCOME LIKE 'Spayed%' OR SEX_UPON_OUTCOME LIKE 'Neutered%')
ORDER BY ANIMAL_ID

