# SELECT 
#     YEAR(OS.SALES_DATE) AS YEAR,
#     MONTH(OS.SALES_DATE) AS MONTH,
#     (SELECT GENDER
#      FROM USER_INFO UI
#      JOIN ONLINE_SALE OS ON UI.USER_ID = OS.USER_ID
#      WHERE OS.SALES_DATE LIKE '2022-01%') AS GENDER
# FROM USER_INFO UI
# JOIN ONLINE_SALE OS ON UI.USER_ID = OS.USER_ID
# # WHERE UI.USER_ID IN (SELECT USER_ID FROM ONLINE_SALE WHERE SALES_DATE LIKE '2022-01%')
# ORDER BY YEAR, MONTH

SELECT 
    YEAR(OS.SALES_DATE) AS YEAR, 
    MONTH(OS.SALES_DATE) AS MONTH,
    GENDER,
    COUNT(DISTINCT UI.USER_ID) AS USERS
FROM USER_INFO UI
JOIN ONLINE_SALE OS ON UI.USER_ID = OS.USER_ID
WHERE UI.USER_ID IN (SELECT USER_ID FROM USER_INFO WHERE GENDER IS NOT NULL)
GROUP BY GENDER, MONTH, YEAR
ORDER BY YEAR, MONTH, GENDER