# SELECT 
#     B.FISH_COUNT, 
#     A.FISH_NAME
# FROM (
#     SELECT FISH_TYPE, COUNT(*) AS FISH_COUNT
#     FROM FISH_INFO
#     GROUP BY FISH_TYPE
# ) B
# JOIN FISH_NAME_INFO A 
# ON A.FISH_TYPE = B.FISH_TYPE
# ORDER BY FISH_COUNT DESC

SELECT 
    COUNT(*) AS FISH_COUNT,
    A.FISH_NAME
FROM FISH_INFO B
JOIN FISH_NAME_INFO A
ON A.FISH_TYPE = B.FISH_TYPE
GROUP BY A.FISH_NAME
ORDER BY FISH_COUNT DESC;