# SELECT U.USER_ID, U.NICKNAME, SUM(B.PRICE) AS TOTAL_PRICE
# FROM USED_GOODS_BOARD B
# JOIN USED_GOODS_USER U ON B.WRITER_ID = U.USER_ID
# WHERE (B.WRITER_ID) IN (SELECT WRITER_ID FROM USED_GOODS_BOARD GROUP BY WRITER_ID HAVING SUM(PRICE) >= 700000)
# GROUP BY U.USER_ID, U.NICKNAME
# ORDER BY TOTAL_PRICE

SELECT U.USER_ID, U.NICKNAME, SUM(PRICE) AS TOTAL_SALES 
FROM USED_GOODS_BOARD B
JOIN USED_GOODS_USER U ON B.WRITER_ID = U.USER_ID
WHERE B.STATUS IN ('DONE')
GROUP BY B.WRITER_ID, U.NICKNAME
HAVING SUM(PRICE) >= 700000
ORDER BY TOTAL_SALES