SELECT
    A.EMP_NO,
    B.EMP_NAME,
    A.GRADE,
    (CASE WHEN A.GRADE = 'S' THEN B.SAL * 0.2
          WHEN A.GRADE = 'A' THEN B.SAL * 0.15
          WHEN A.GRADE = 'B' THEN B.SAL * 0.1
          ELSE 0 END) AS BONUS
FROM (SELECT
    EMP_NO,
    (CASE WHEN AVG(G.SCORE) >= 96 THEN 'S'
          WHEN AVG(G.SCORE) >= 90 THEN 'A'
          WHEN AVG(G.SCORE) >= 80 THEN 'B'
          ELSE 'C' END) AS GRADE
FROM HR_GRADE G
GROUP BY EMP_NO) A
JOIN HR_EMPLOYEES B ON A.EMP_NO = B.EMP_NO
ORDER BY EMP_NO