# SELECT
#     B.COUNT AS FISH_COUNT,
#     B.MAX AS MAX_LENGTH,
#     B.FISH_TYPE
# FROM (
#     SELECT
#         COUNT(*) AS COUNT,
#         MAX(LENGTH) AS MAX,
#         AVG(LENGTH) AS AVG,
#         FISH_TYPE
#     FROM FISH_INFO
#     GROUP BY FISH_TYPE
# ) B
# WHERE B.AVG >= 33

SELECT
    COUNT(*) AS FISH_COUNT,
    MAX(LENGTH) AS MAX_LENGTH,
    FISH_TYPE
FROM FISH_INFO
GROUP BY FISH_TYPE
HAVING AVG(IFNULL(LENGTH, 10)) >= 33
ORDER BY FISH_TYPE